-- Find the total sales (Quantity * UnitPrice) for each product and display ProductName, TotalSales, sorted in descending order.

select * from product;
select * from orderdetail;

SELECT p.productName, SUM(o.quantity * o.unitPrice) as Total_Sales
FROM orderdetail o
JOIN product p
ON o.productId = p.entityId
GROUP BY p.productName
ORDER BY SUM(o.quantity * o.unitPrice) DESC;


-- Calculate the total revenue generated by each customer. Display CustomerID, CustomerName, and TotalRevenue.

select c.entityId,c.contactName as Customer_Name,sum(o.unitPrice*o.quantity) Total_Revenue 
from customer c inner join salesorder s
on c.entityId=s.customerId
inner join orderdetail o
on s.entityId=o.orderId
group by c.entityId,c.companyName;